language: ruby
rvm:
- 2.2.2
before_script:
- npm install
- npm install -g grunt-cli
- gem install sass
script: npm build
after_success: bash ./scripts/cibuild.sh
branches:
  only:
  - master
git:
  depth: 1
env:
  global:
    - GH_REF: github.com/GovernanceDataAlliance/goal16.git
